// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAS_API.Data;

#nullable disable

namespace PAS_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231107023501_AddForeignKeyToUnitTable")]
    partial class AddForeignKeyToUnitTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PAS_API.Model.TUnit", b =>
                {
                    b.Property<long?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long?>("ID"));

                    b.Property<decimal?>("Bgn_mtr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BiayaAdmin")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CaraBayar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaraBayarDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Dpp_bgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Dpp_tnh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("FIDCluster")
                        .HasColumnType("bigint");

                    b.Property<long?>("FUnit")
                        .HasColumnType("bigint");

                    b.Property<string>("FlagStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HargaJualNet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HistoryData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KelasBangunan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KelasBumi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LuasBangunan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("LuasTanah")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaterialIDSAP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NilaiKpr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NoAdendumPPJB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoPPJB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderCancellation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodeSewa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Ppn_bgn")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ppn_tnh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromoCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TglAdendumPPJB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TglPembukuan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TglPpjb")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TglRencanaSerahTerima")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TglSO")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TglSewa")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Tnh_mtr")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("FUnit");

                    b.ToTable("tblT_Unit");
                });

            modelBuilder.Entity("PAS_API.Model.Unit", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<string>("BACode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BADesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Block")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlockDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DayaListrik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FIDCluster")
                        .HasColumnType("bigint");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hadap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HadapDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HistoryData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lantai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LuasNett")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MataAngin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoPUPR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SLocDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesOrg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sbu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SbuDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sektor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnitIDOld")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UoMeasure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Watt")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("tblM_Unit");
                });

            modelBuilder.Entity("PAS_API.Model.TUnit", b =>
                {
                    b.HasOne("PAS_API.Model.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("FUnit");

                    b.Navigation("Unit");
                });
#pragma warning restore 612, 618
        }
    }
}
